### ISSUE TITLE
Reddish colors

### ISSUE THREAD

**Issue by Ilya87** [pinterf/AviSynthPlus#26]
VC1 video, decoded with AviSynth+ r2772 has reddish colors.

K-Lite Codec Pack settings window:
![58](https://user-images.githubusercontent.com/1446573/53302929-5632a700-3875-11e9-8079-880b1a98620f.png)

FFmpegSource2("Equilibrium-001.mkv")
![ffmpegsource2](https://user-images.githubusercontent.com/1446573/53302798-6b0e3b00-3873-11e9-906c-ea8467be9b7e.png)

DirectShowSource("Equilibrium-001.mkv")
![orig](https://user-images.githubusercontent.com/1446573/53302816-bde7f280-3873-11e9-9e27-649f83d29b2d.png)

ffmpeg.exe -i Equilibrium-001.mkv -frames:v 1 ff.png
![ffmpeg](https://user-images.githubusercontent.com/1446573/53302863-4c5c7400-3874-11e9-9bde-af1e0074a115.png)

All screenshots (when AviSynth+ was used) above were taken with ffmpeg: ffmpeg.exe -i 01.avs -frames:v 1 ff.png

As you can see ffmpeg decoder provides natural colors.

http://www.framecompare.com/image-compare/screenshotcomparison/10J1NNNU

**Comment by Ilya87** [comment]
Forgot to mention - color primaries, range, color matrix, trasfer parameters are set in mkv.

**Comment by pinterf** [comment]
It's very unlike that I can help with it. Source filters do decoding stuff, AviSynth+ passes it through, and then you have again something at the end of the pipe. Avisynth does not able to preserve original clip properties. Reddish cast is usually happens when rec.601 vs. rec709 is mismatched somewhere in the conversions. I recommend asking this question on a public forum, such as https://forum.doom9.org/forumdisplay.php?f=33 Community users know hundred times more than I do as a developer.

**Comment by Ilya87** [comment]
Thank you for the hint! The solution that I found by myself - ffmpeg.exe -colorspace bt709 -color_range tv -i 01.avs ... So, it's ffmpeg "feature".
