### ISSUE TITLE
Avisynth+ x86 and Windows Server 2008 R2 x64

### ISSUE THREAD

**Issue by TbtBI** [pinterf/AviSynthPlus#32]
When trying SupTitle plugin with Avisynth+ x86 on Windows Server 2008 R2 x64 Standard, there is no output and the Avisynth process is hanging - [example](https://images2.imgbox.com/74/04/rubc9Lvr_o.png). Tested different older versions, the behavior is the same.
Removing SupTitle, there is no problem - [example](http://imgbox.com/TMXALC6p).
Using SupTitle plugin with AviSynth 2.6.0/2.6.1, there is no problem - [example](http://imgbox.com/1fNRS4zL).
Using SupTitle x64 and Avisynth+ x64, there is no problem.
[Here](https://www.upload.ee/files/9912104/plugins.7z.html) SupTitle plugin x86.
On Windows 10 there is no such problem.

**Comment by fuchanghao** [comment]
Check if you don't install .net framework 4.5 or newer.

**Comment by TbtBI** [comment]
I had 4.72 installed. Uninstalled and installed [4.0](https://www.softpedia.com/get/Programming/Other-Programming-Files/Microsoft-NET-Framework-Client-Profile.shtml), but no change - Avisynth+ x86 is still hanging.

**Comment by pinterf** [comment]
By this page .Net 4.0 is needed, maybe client profile is not enough?
http://avisynth.nl/index.php?title=SupTitle

Unfortunately there are no source code is available (author had hdd crash), nor can I reproduce the problem.

As I see in the forum, Stax76 had also random problems.
https://forum.doom9.org/showthread.php?t=148167&page=7

If the problem is of software (and not .net environment/c++ redistributable) related, we cannot do much. Sometimes things just work accidentally on one system and not on another. Maybe the plugin uses assumptions that are not true for all systems. Or since it's a hybrid C/C# (?) filter, the interface wrappers are more sensitive to the internal structures and exact sizes of basic Avisynth data types. E.g. introducing alpha plane in AVS+ one of the basic structures became 4-8 bytes larger than it was in the old times. As this plugin is using a v2.5 interface which had a _lot_ of ugly "baked" code which was partly removed in Avisynth 2.6 and on, it's more prone to such scenarios.

**Comment by TbtBI** [comment]
I tried [.Net 4.0 Full](https://www.microsoft.com/en-us/download/details.aspx?id=17718), but no change.

Thanks for the replies. I guess this ticket could be closed.
